from medical_store.views.company_details_view import CompanyDetailsViewSets
from medical_store.views.count_view import CountAPI
from medical_store.views.expiry_view import ExpiryAPI
from medical_store.views.medicine_inventory_view import MedicineInventoryViewSets
from medical_store.views.purchase_view import PurchaseViewSets
from medical_store.views.sales_view import SalesViewSets
from medical_store.views.stock_view import StockAPI
