# Generated by Django 3.1.8 on 2021-06-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="country",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="userdetails",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
